### PR TITLE
only emit digital read events on value change; closes #2

### LINKED ISSUE #2: digitalRead should only emit on change
Hi,

Thanks for this plugin.  I believe that the behavior of `digitalRead` in `raspi-io-core` diverges from the behavior of `StandardFirmata`.

From the [StandardFirmata](https://github.com/firmata/arduino/blob/5d9b2986eebc4bcb29389ba9522f047b11aa8573/examples/StandardFirmata/StandardFirmata.ino) implementation, we see that Firmata will only report a value back to Johnny-Five if that value [has changed](https://github.com/firmata/arduino/blob/5d9b2986eebc4bcb29389ba9522f047b11aa8573/examples/StandardFirmata/StandardFirmata.ino#L227).

For digital reads, Johnny-Five will typically [wrap this in a 5-7ms "debounce"](https://github.com/rwaldron/johnny-five/blob/master/lib/switch.js#L37), but otherwise its default IO module does not interfere.  The rate at which a digital read will be emitted by Johnny-Five is then the responsibility of the IO module itself.

If we wire an Arduino like so:

screenshot

and use the following example code:

```js
var five = require("johnny-five");
var board = new five.Board();

board.on("ready", function() {
  var spdt = new five.Switch(8);
  spdt.on("open", function() {
    console.error('open');
  });

  spdt.on("close", function() {
    console.error('close');
  });
});
```

Either `open` or `close` will be output *once* upon board readiness, and *only* then again if you flip the SPDT switch (assuming a quiet circuit).

If we instead plug this breadboard into a Raspberry Pi (in my case, a Zero, using GPIO4):

image

and then run the same code, `open` and `close` are output *many times per second*.

cc @rwaldron if he cares to fact-check me :wink:

### PR DESCRIPTION
**Pull request by boneskull**
This seems to work as I would expect and resolves the problem I reported in #2.

I regenerated the distfile, since it's under VCS (should it be?), but I can pull this out if needed.

### CODE REVIEW

**Comment by boneskull** [comment]
~~hmm, something is amiss.~~ fixed

**Comment by nebrius** [comment]
> I regenerated the distfile, since it's under VCS (should it be?), but I can pull this out if needed.

yes it should be there, thanks! If we didn't include it in the repo/npm module, it would need to be built at install time on the user's Raspberry Pi. In addition to making install times longer, there's always the chance something could go wrong in the process. General rule of thumb for any npm module is to build before you publish, not after install.

**Review by nebrius — APPROVED** [review]
LGTM, thank you for taking the time to dig in and fix this! And once again, my apologies for missing this!

**Comment by boneskull** [comment]
no I mean you can publish a diatribe without it being under VCS.

**Comment by boneskull** [comment]
lol autocorrect. distfile not diatribe

**Comment by nebrius** [comment]
Ah, gotcha. TBH I just like checking the dist files in. That way I can see how a build changes (especially when upgrading build tools) and I can get a heads up quicker if there’s something funky with the build, and what change caused it.

**Pull request merged**
